__default__:
    time: 00:30:00
    job-name:  RNAseq
    account: project_2001454
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001454/PigMeatQuality/logs/
    
star_create_index:
    job-name: star_index
    time: 08:00:00
    partition: small
    mem-per-cpu: 4000
    cpus-per-task: 12

fastqc_quality_control:
    job-name: fastqc
    time: 01:00:00
    partition: small
    cpus-per-task: 12

multiqc_quality_control:
    job-name: multiqc
    time: 00:10:00
    partition: small
    cpus-per-task: 12
    
cutadapt_trim_reads:
    job-name: cutadapt
    time: 01:00:00
    partition: small
    cpus-per-task: 1

fastqc_quality_control_cutadapt:
    job-name: fastqc_cutadapt
    time: 01:00:00
    partition: small
    cpus-per-task: 12

multiqc_quality_control_cutadapt:
    job-name: multiqc_cutadapt
    time: 00:10:00
    partition: small
    cpus-per-task: 12
    
star_map_reads:
    job-name: star_mapReads
    time: 04:00:00
    partition: small
    cpus-per-task: 12
    
featureCounts_quantify:
    job-name: fc_quantify
    time: 02:00:00
    partition: small
    cpus-per-task: 12
    
rsem_create_index:
    job-name: rsem_index
    time: 0-10:00:00
    partition: small
    cpus-per-task: 12
    
rsem_calculate_expressions:
    job-name: rsem_quant
    time: 0-04:00:00
    partition: small
    cpus-per-task: 12

samtools_bam_to_sortedBam:
    job-name: st_sort
    time: 0-04:00:00
    partition: small
    cpus-per-task: 12
    
samtools_indexFasta:
    job-name: st_index
    time: 0-04:00:00
    partition: small
    cpus-per-task: 12
    
samtools_mpileup:
    job-name: st_mpile
    time: 3-00:00:00
    partition: small
    cpus-per-task: 20
    mem-per-cpu: 10000
    
samtools_callvariants:
    job-name: st_vcfcall
    time: 3-00:00:00
    partition: small
    cpus-per-task: 20
    mem-per-cpu: 10000
    
samtools_filtervariants:
    job-name: st_vcffilter
    time: 0-01:00:00
    partition: small
    cpus-per-task: 20
    mem-per-cpu: 10000
