project-folder: "/scratch/project_2001454/PigMeatQuality"                                               # Path to the project folder
samples: "/scratch/project_2001454/PigMeatQuality/samples"                                              # Path to the sample file

genome: /scratch/project_2001454/PigMeatQuality/Reference/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa        # Path to the reference genome
annot:  /scratch/project_2001454/PigMeatQuality/Reference/Sus_scrofa.Sscrofa11.1.97.gtf                 # Path to the reference annotation

star-index:  /scratch/project_2001454/PigMeatQuality/Reference/STAR2.7.2b                               # Path to the STAR index to be created

params:
  cutadapt:
    phread_score: "30"
    adapter: "/scratch/project_2001454/PigMeatQuality/Reference/TruSeq3-SE.fa"
    min_length: "20"
